{% set name = "jupyter_to_medium" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3a7aa62cf49d88c3ac0bf7531c6e80ddec90e055ecf077b1b5f218bb7d4b4ab

build:
  number: 0
  noarch: python
  entry_points:
    - jupyter_to_medium=jupyter_to_medium._command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - matplotlib-base >=3.1
    - nbconvert
    - numpy
    - python >=3.6
    - requests

test:
  imports:
    - jupyter_to_medium
  commands:
    - pip check
    - jupyter_to_medium --help
  requires:
    - pip

about:
  home: https://dexplo.org/jupyter_to_medium
  summary: Publish a Jupyter Notebook as a Medium blogpost
  license: MIT
  license_file: LICENSE
  doc_url: https://dexplo.org/jupyter_to_medium
  dev_url: https://github.com/dexplo/jupyter_to_medium

extra:
  recipe-maintainers:
    - tdpetrou
